//! Oracle test framework for validating ferray against `NumPy` fixture outputs.
//!
//! Loads JSON fixtures generated by `scripts/generate_fixtures.py`, parses
//! array data (f64, f32, complex, bool, string), constructs ferray arrays,
//! and compares outputs using ULP (Units in the Last Place) tolerances.

// Oracle comparison crosses `usize` shape data through `f64` JSON, decodes
// bit patterns into `f32`/`f64` for ULP comparison, and tolerates the full
// matrix of dtype roundtrips that the fixture corpus targets.
#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss,
    clippy::cast_lossless,
    clippy::float_cmp,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::many_single_char_names,
    clippy::similar_names,
    clippy::items_after_statements,
    clippy::option_if_let_else,
    clippy::too_long_first_doc_paragraph,
    clippy::needless_pass_by_value,
    clippy::match_same_arms
)]

use ferray_core::Array;
use ferray_core::dimension::IxDyn;
use ferray_core::error::FerrayResult;
use num_complex::Complex;
use serde::Deserialize;
use std::path::{Path, PathBuf};

// Re-export serde_json::Value so test files can use it without adding serde_json
pub use serde_json;

/// Minimum ULP tolerance applied to all oracle comparisons.
///
/// Tightened to 10 ULP (#47) to characterize the real pure-Rust
/// precision envelope. Pure-Rust implementations (faer, rustfft,
/// `serde_json`) generally round to within a few ULPs of NumPy's
/// C/Fortran stack (LAPACK, pocketfft); 10 ULP gives a meaningful
/// signal when ferray drifts further than expected, while leaving
/// headroom for the legitimate last-bit divergences caused by
/// different summation orders / kernel choices.
///
/// 10 ULP on f64 still guarantees ~15.7 correct decimal digits —
/// well beyond any scientific measurement precision.
///
/// In several cases (polyfit, roots) ferray's iterative refinement
/// produces answers *closer to mathematical truth* than NumPy's. The
/// tolerance accommodates divergence in both directions.
///
/// Per-fixture overrides (set higher in individual `tolerance_ulps`
/// JSON fields) are still honoured for ops with known wider envelopes
/// (e.g. matmul/FFT at scale, where O(n)/O(log n) error growth is
/// inherent).
pub const MIN_ULP_TOLERANCE: u64 = 10;

/// Near-zero absolute tolerance for f64 ULP comparisons.
///
/// Values with magnitude below this are considered indistinguishable
/// from rounding error and treated as a match regardless of ULP
/// distance (which is meaningless near zero: adjacent subnormals
/// differ by millions of ULPs).
///
/// Decoupled from `MIN_ULP_TOLERANCE` (#47): the noise floor is an
/// absolute-value cutoff with units of "smallest distinguishable
/// f64 magnitude", whereas the ULP tolerance is a relative bit-count
/// cutoff. Tightening the ULP tolerance shouldn't tighten the
/// noise floor (and vice versa) — the two characterize different
/// failure modes. Set at `128 * f64::EPSILON ≈ 2.84e-14`, which
/// covers the typical near-zero output of pure-Rust FFT/linalg
/// (rustfft sine returns ~6e-15 instead of NumPy's exact 0 at the
/// fundamental frequency).
pub const F64_NOISE_FLOOR: f64 = 128.0 * f64::EPSILON;

/// f32 counterpart. Decoupled from `MIN_ULP_TOLERANCE` for the same
/// reasons as `F64_NOISE_FLOOR`.
pub const F32_NOISE_FLOOR: f32 = 128.0 * f32::EPSILON;

// ---------------------------------------------------------------------------
// JSON schema types
// ---------------------------------------------------------------------------

/// Top-level structure of a fixture JSON file.
#[derive(Debug, Deserialize)]
pub struct FixtureSuite {
    /// The `NumPy` function name (e.g., "numpy.sin").
    pub function: String,
    /// The ferray function path (e.g., "`ferray_ufunc::sin`").
    pub ferray_function: String,
    /// Individual test cases with inputs, expected outputs, and tolerances.
    pub test_cases: Vec<TestCase>,
}

/// A single test case within a fixture file.
#[derive(Debug, Deserialize)]
pub struct TestCase {
    /// Descriptive name (e.g., "`standard_f64`", "`special_values`").
    pub name: String,
    /// Input parameters as a JSON object. Keys vary by function.
    pub inputs: serde_json::Value,
    /// Expected output.
    pub expected: serde_json::Value,
    /// Maximum allowed ULP distance between actual and expected.
    pub tolerance_ulps: u64,
}

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

/// Load a fixture suite from a JSON file.
#[must_use]
pub fn load_fixture(path: &Path) -> FixtureSuite {
    let contents = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read fixture file {}: {e}", path.display()));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("failed to parse fixture JSON {}: {e}", path.display()))
}

/// Return the path to the workspace `fixtures/` directory.
///
/// Works from any crate in the workspace by walking up from `CARGO_MANIFEST_DIR`.
#[must_use]
pub fn fixtures_dir() -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = Path::new(&manifest);
    // Walk up to find the fixtures dir (handles both crate and workspace root)
    let mut dir = manifest_path;
    loop {
        let candidate = dir.join("fixtures");
        if candidate.is_dir() {
            return candidate;
        }
        dir = match dir.parent() {
            Some(p) => p,
            None => panic!(
                "could not find fixtures/ directory from {}",
                manifest_path.display()
            ),
        };
    }
}

// ---------------------------------------------------------------------------
// JSON data parsing
// ---------------------------------------------------------------------------

/// Parse a JSON value into a `Vec<f64>`, handling special string values
/// ("NaN", "Inf", "-Inf") and scalar/array formats.
pub fn parse_f64_data(value: &serde_json::Value) -> Vec<f64> {
    match value {
        serde_json::Value::Array(arr) => arr.iter().map(parse_f64_value).collect(),
        serde_json::Value::Number(n) => vec![n.as_f64().unwrap()],
        serde_json::Value::String(s) => vec![parse_f64_special(s)],
        _ => panic!("unexpected data format: {value}"),
    }
}

/// Parse a single JSON value to f64.
#[must_use]
pub fn parse_f64_value(v: &serde_json::Value) -> f64 {
    match v {
        serde_json::Value::Number(n) => n.as_f64().unwrap(),
        serde_json::Value::String(s) => parse_f64_special(s),
        _ => panic!("unexpected value: {v}"),
    }
}

fn parse_f64_special(s: &str) -> f64 {
    match s {
        "NaN" => f64::NAN,
        "Inf" | "Infinity" => f64::INFINITY,
        "-Inf" | "-Infinity" => f64::NEG_INFINITY,
        other => other
            .parse::<f64>()
            .unwrap_or_else(|_| panic!("cannot parse '{other}' as f64")),
    }
}

/// Parse a JSON value into a `Vec<f32>`.
#[must_use]
pub fn parse_f32_data(value: &serde_json::Value) -> Vec<f32> {
    match value {
        serde_json::Value::Array(arr) => arr.iter().map(|v| parse_f64_value(v) as f32).collect(),
        serde_json::Value::Number(n) => vec![n.as_f64().unwrap() as f32],
        serde_json::Value::String(s) => vec![parse_f64_special(s) as f32],
        _ => panic!("unexpected data format: {value}"),
    }
}

/// Parse complex data from `[{"re": ..., "im": ...}, ...]` format.
///
/// The `re` and `im` fields may be numeric literals OR JSON strings
/// like `"NaN"`, `"Inf"`, or `"-Inf"` — Python's JSON serializer writes
/// non-finite floats as strings because the JSON grammar has no NaN/Inf
/// tokens. Previously this function called `as_f64().unwrap()` which
/// panicked on those string values; we now route both fields through
/// [`parse_f64_value`] so NaN/Inf round-trip cleanly through the oracle
/// fixtures.
#[must_use]
pub fn parse_complex_data(value: &serde_json::Value) -> Vec<Complex<f64>> {
    match value {
        serde_json::Value::Array(arr) => arr
            .iter()
            .map(|v| {
                let re = parse_f64_value(&v["re"]);
                let im = parse_f64_value(&v["im"]);
                Complex::new(re, im)
            })
            .collect(),
        serde_json::Value::Object(obj) => {
            let re = parse_f64_value(&obj["re"]);
            let im = parse_f64_value(&obj["im"]);
            vec![Complex::new(re, im)]
        }
        _ => panic!("unexpected complex format: {value}"),
    }
}

/// Parse a shape array from JSON (e.g., `[3, 4]`).
#[must_use]
pub fn parse_shape(value: &serde_json::Value) -> Vec<usize> {
    value
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect()
}

/// Parse boolean array data from JSON.
#[must_use]
pub fn parse_bool_data(value: &serde_json::Value) -> Vec<bool> {
    match value {
        serde_json::Value::Array(arr) => arr.iter().map(|v| v.as_bool().unwrap()).collect(),
        _ => panic!("unexpected bool data: {value}"),
    }
}

/// Parse string array data from JSON.
#[must_use]
pub fn parse_string_data(value: &serde_json::Value) -> Vec<String> {
    match value {
        serde_json::Value::Array(arr) => arr
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect(),
        _ => panic!("unexpected string data: {value}"),
    }
}

/// Parse integer (usize) array data from JSON.
#[must_use]
pub fn parse_usize_data(value: &serde_json::Value) -> Vec<usize> {
    match value {
        serde_json::Value::Array(arr) => arr.iter().map(|v| v.as_u64().unwrap() as usize).collect(),
        serde_json::Value::Number(n) => vec![n.as_u64().unwrap() as usize],
        _ => panic!("unexpected usize data: {value}"),
    }
}

// ---------------------------------------------------------------------------
// Array construction from fixture data
// ---------------------------------------------------------------------------

/// Build an `Array<f64, IxDyn>` from a fixture input object
/// (expects `{"data": [...], "shape": [...], "dtype": "float64"}`).
#[must_use]
pub fn make_f64_array(value: &serde_json::Value) -> Array<f64, IxDyn> {
    let data = parse_f64_data(&value["data"]);
    let shape = parse_shape(&value["shape"]);
    Array::from_vec(IxDyn::new(&shape), data).unwrap()
}

/// Build an `Array<f32, IxDyn>` from a fixture input object.
#[must_use]
pub fn make_f32_array(value: &serde_json::Value) -> Array<f32, IxDyn> {
    let data = parse_f32_data(&value["data"]);
    let shape = parse_shape(&value["shape"]);
    Array::from_vec(IxDyn::new(&shape), data).unwrap()
}

/// Build an `Array<Complex<f64>, IxDyn>` from a fixture input object.
#[must_use]
pub fn make_complex_array(value: &serde_json::Value) -> Array<Complex<f64>, IxDyn> {
    let data = parse_complex_data(&value["data"]);
    let shape = parse_shape(&value["shape"]);
    Array::from_vec(IxDyn::new(&shape), data).unwrap()
}

/// Build an `Array<bool, IxDyn>` from a fixture input object.
#[must_use]
pub fn make_bool_array(value: &serde_json::Value) -> Array<bool, IxDyn> {
    let data = parse_bool_data(&value["data"]);
    let shape = parse_shape(&value["shape"]);
    Array::from_vec(IxDyn::new(&shape), data).unwrap()
}

/// Get the dtype string from a fixture input object.
#[must_use]
pub fn get_dtype(value: &serde_json::Value) -> &str {
    value["dtype"].as_str().unwrap_or("float64")
}

/// Check if a test case should be skipped (scalar inputs, empty arrays, or
/// non-f64 dtypes for f64-only runners).
#[must_use]
pub fn should_skip_f64(input: &serde_json::Value) -> bool {
    let dtype = get_dtype(input);
    if dtype != "float64" {
        return true;
    }
    let shape = parse_shape(&input["shape"]);
    // Skip 0-d scalars (shape=[]) — they can't be constructed as IxDyn arrays
    if shape.is_empty() {
        return true;
    }
    false
}

// ---------------------------------------------------------------------------
// ULP comparison
// ---------------------------------------------------------------------------
//
// `is_scalar_expected` used to live here but was never called; the
// scalar-detection path goes through `parse_shape(..).is_empty()`
// directly (#318).

/// Sign bit masks for clearing the top bit of an IEEE 754 float when
/// converting to a magnitude-in-ULPs-from-zero.
const F64_SIGN_MASK: u64 = 0x8000_0000_0000_0000;
const F32_SIGN_MASK: u32 = 0x8000_0000;

/// Compute ULP distance between two f64 values.
///
/// Same sign: bit-subtract, since IEEE 754 lays out floats so that the
/// integer representation of same-sign floats increases monotonically.
///
/// Different signs: route through zero — the distance from `a` to zero
/// (which is just `|a|`'s bit pattern with the sign bit masked off, since
/// IEEE 754 negatives are sign-magnitude, *not* two's complement) plus
/// the same for `b`. The previous implementation cast `to_bits()` as
/// `i64` and called `unsigned_abs()`, which produced a two's-complement
/// magnitude and overstated the cross-sign distance by up to 2^53.
///
/// Returns `None` if either value is NaN (NaN comparison is handled
/// separately by [`assert_f64_ulp`]).
#[must_use]
pub fn ulp_distance_f64(a: f64, b: f64) -> Option<u64> {
    if a.is_nan() || b.is_nan() {
        return None;
    }
    if a == b {
        // Also covers +0.0 == -0.0.
        return Some(0);
    }
    // Near-zero noise floor: values below this are indistinguishable
    // from rounding error, so we report an exact match *and* require
    // the absolute difference to also be within the floor. The extra
    // `(a - b).abs() < floor` check avoids the opposite-sign pair
    // `(+floor/2, -floor/2)` being reported as identical even though
    // their cross-sign ULP distance is huge (#321).
    if a.abs() < F64_NOISE_FLOOR && b.abs() < F64_NOISE_FLOOR && (a - b).abs() < F64_NOISE_FLOOR {
        return Some(0);
    }
    if a.is_sign_negative() != b.is_sign_negative() {
        // Cross-sign: distance-through-zero in sign-magnitude ULPs.
        let a_mag = a.to_bits() & !F64_SIGN_MASK;
        let b_mag = b.to_bits() & !F64_SIGN_MASK;
        return Some(a_mag + b_mag);
    }
    // Same sign: bit-level subtraction. For same-sign floats the
    // integer reinterpretation is monotonic in magnitude, so the
    // difference is a valid ULP distance.
    let a_bits = a.to_bits();
    let b_bits = b.to_bits();
    Some(a_bits.max(b_bits) - a_bits.min(b_bits))
}

/// Compute ULP distance between two f32 values. See [`ulp_distance_f64`]
/// for the algorithm — this is the same thing with 32-bit masks.
#[must_use]
pub fn ulp_distance_f32(a: f32, b: f32) -> Option<u64> {
    if a.is_nan() || b.is_nan() {
        return None;
    }
    if a == b {
        return Some(0);
    }
    if a.abs() < F32_NOISE_FLOOR && b.abs() < F32_NOISE_FLOOR && (a - b).abs() < F32_NOISE_FLOOR {
        return Some(0);
    }
    if a.is_sign_negative() != b.is_sign_negative() {
        let a_mag = a.to_bits() & !F32_SIGN_MASK;
        let b_mag = b.to_bits() & !F32_SIGN_MASK;
        return Some(u64::from(a_mag) + u64::from(b_mag));
    }
    let a_bits = a.to_bits();
    let b_bits = b.to_bits();
    Some(u64::from(a_bits.max(b_bits) - a_bits.min(b_bits)))
}

/// Assert that two f64 values match within the given ULP tolerance.
///
/// NaN == NaN is considered a match. Inf signs must agree.
/// Near-zero values (below [`F64_NOISE_FLOOR`]) are handled inside
/// [`ulp_distance_f64`]; this function previously had its own
/// duplicate noise-floor branch (#315).
pub fn assert_f64_ulp(actual: f64, expected: f64, tolerance: u64, context: &str) {
    // NaN matches NaN
    if actual.is_nan() && expected.is_nan() {
        return;
    }
    assert!(
        actual.is_nan() == expected.is_nan(),
        "{context}: NaN mismatch — actual={actual}, expected={expected}"
    );
    // Inf must match sign
    if actual.is_infinite() && expected.is_infinite() {
        assert_eq!(
            actual.is_sign_positive(),
            expected.is_sign_positive(),
            "{context}: infinity sign mismatch"
        );
        return;
    }
    // `ulp_distance_f64` only returns `None` when one of the inputs is
    // NaN — handled above — so at this point we always get `Some`.
    // The unreachable arm was the subject of #317.
    let dist = ulp_distance_f64(actual, expected)
        .expect("ulp_distance_f64 returned None despite NaN guard above");
    assert!(
        dist <= tolerance,
        "{context}: ULP distance {dist} exceeds tolerance {tolerance} \
         (actual={actual}, expected={expected})"
    );
}

/// Assert that two f32 values match within the given ULP tolerance.
///
/// f32 now uses the same noise-floor shape as f64 via
/// [`ulp_distance_f32`] (#316).
pub fn assert_f32_ulp(actual: f32, expected: f32, tolerance: u64, context: &str) {
    if actual.is_nan() && expected.is_nan() {
        return;
    }
    assert!(
        actual.is_nan() == expected.is_nan(),
        "{context}: NaN mismatch — actual={actual}, expected={expected}"
    );
    if actual.is_infinite() && expected.is_infinite() {
        assert_eq!(
            actual.is_sign_positive(),
            expected.is_sign_positive(),
            "{context}: infinity sign mismatch"
        );
        return;
    }
    let dist = ulp_distance_f32(actual, expected)
        .expect("ulp_distance_f32 returned None despite NaN guard above");
    assert!(
        dist <= tolerance,
        "{context}: ULP distance {dist} exceeds tolerance {tolerance} \
         (actual={actual}, expected={expected})"
    );
}

/// Compare two f64 slices element-by-element within ULP tolerance.
pub fn assert_f64_slice_ulp(actual: &[f64], expected: &[f64], tolerance: u64, case_name: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "case '{case_name}': length mismatch ({} vs {})",
        actual.len(),
        expected.len()
    );
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_f64_ulp(
            a,
            e,
            tolerance,
            &format!("case '{case_name}' [element {i}]"),
        );
    }
}

/// Compare two f32 slices element-by-element within ULP tolerance.
pub fn assert_f32_slice_ulp(actual: &[f32], expected: &[f32], tolerance: u64, case_name: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "case '{case_name}': length mismatch ({} vs {})",
        actual.len(),
        expected.len()
    );
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_f32_ulp(
            a,
            e,
            tolerance,
            &format!("case '{case_name}' [element {i}]"),
        );
    }
}

/// Mirror of [`should_skip_f64`] for f32: skip non-float dtypes and 0-d
/// scalars. f64 fixtures are accepted because they cast down to f32
/// cleanly within the f32 ULP tolerance budget.
#[must_use]
pub fn should_skip_f32(input: &serde_json::Value) -> bool {
    let dtype = get_dtype(input);
    if dtype != "float32" && dtype != "float64" {
        return true;
    }
    let shape = parse_shape(&input["shape"]);
    if shape.is_empty() {
        return true;
    }
    false
}

/// Materialize an f32 array from a fixture value, casting from f64 if the
/// fixture stores a native float64 column. Mirrors [`make_f64_array`] for
/// f32 oracle paths (#213).
#[must_use]
pub fn make_f32_array_from_any(value: &serde_json::Value) -> Array<f32, IxDyn> {
    let dtype = get_dtype(value);
    let shape = parse_shape(&value["shape"]);
    if dtype == "float32" {
        make_f32_array(value)
    } else {
        let data: Vec<f32> = parse_f64_data(&value["data"])
            .into_iter()
            .map(|x| x as f32)
            .collect();
        Array::<f32, IxDyn>::from_vec(IxDyn::new(&shape), data).unwrap()
    }
}

/// Compare two complex f64 slices element-by-element within ULP tolerance.
/// Each component (real and imaginary) is compared independently.
pub fn assert_complex_slice_ulp(
    actual: &[Complex<f64>],
    expected: &[Complex<f64>],
    tolerance: u64,
    case_name: &str,
) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "case '{case_name}': length mismatch ({} vs {})",
        actual.len(),
        expected.len()
    );
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_f64_ulp(
            a.re,
            e.re,
            tolerance,
            &format!("case '{case_name}' [element {i}].re"),
        );
        assert_f64_ulp(
            a.im,
            e.im,
            tolerance,
            &format!("case '{case_name}' [element {i}].im"),
        );
    }
}

// ---------------------------------------------------------------------------
// Generic test runners
// ---------------------------------------------------------------------------

/// Run a unary f64 oracle test: `fn(Array<f64>) -> Array<f64>`.
///
/// Iterates over all f64 test cases in the fixture, constructs the input,
/// calls the function, and compares the output to the expected values.
pub fn run_unary_f64_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<Array<f64, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        if should_skip_f64(input) {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        let data = parse_f64_data(&input["data"]);
        if data.is_empty() && shape == [0] {
            continue;
        }
        let arr = Array::<f64, IxDyn>::from_vec(IxDyn::new(&shape), data).unwrap();
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_f64_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_f64_slice_ulp(
            result_slice,
            &expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run a unary f32 oracle test: `fn(Array<f32>) -> Array<f32>`.
///
/// Mirror of [`run_unary_f64_oracle`] that picks up f32 fixture cases
/// (`dtype == "float32"`). Added to close the "only f64 runners"
/// coverage gap in #319. The f32 path casts the expected data down
/// from the fixture's native f64 representation if the fixture
/// doesn't have a native f32 column.
pub fn run_unary_f32_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f32, IxDyn>) -> FerrayResult<Array<f32, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        let dtype = get_dtype(input);
        // Accept either a native f32 fixture or an f64 fixture cast
        // down — the ULP tolerance at f32 precision will still
        // accommodate the rounding error.
        if dtype != "float32" && dtype != "float64" {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = if dtype == "float32" {
            make_f32_array(input)
        } else {
            let data: Vec<f32> = parse_f64_data(&input["data"])
                .into_iter()
                .map(|x| x as f32)
                .collect();
            Array::<f32, IxDyn>::from_vec(IxDyn::new(&shape), data).unwrap()
        };
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected: Vec<f32> = parse_f64_data(&case.expected["data"])
            .into_iter()
            .map(|x| x as f32)
            .collect();
        let result_slice = result.as_slice().unwrap();
        // f32 ULP tolerance is the f64 tolerance scaled by the
        // relative epsilon ratio, rounded up.
        let f32_tol = case.tolerance_ulps.max(MIN_ULP_TOLERANCE);
        for (i, (&a, &e)) in result_slice.iter().zip(expected.iter()).enumerate() {
            assert_f32_ulp(
                a,
                e,
                f32_tol,
                &format!("case '{}' [element {i}]", case.name),
            );
        }
        tested += 1;
    }
    assert!(tested > 0, "no f32 test cases found in {}", path.display());
}

/// Run a binary f64 oracle test: `fn(Array<f64>, Array<f64>) -> Array<f64>`.
///
/// Expects inputs "a" and "b" in the fixture. As of ferray 0.2.10 broadcast
/// cases are exercised directly (binary ufuncs broadcast by default per
/// issue #379), so a fixture row with mismatched but broadcast-compatible
/// shapes is still tested.
pub fn run_binary_f64_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>, &Array<f64, IxDyn>) -> FerrayResult<Array<f64, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input_a = &case.inputs["a"];
        let input_b = &case.inputs["b"];
        if should_skip_f64(input_a) {
            continue;
        }
        let shape_a = parse_shape(&input_a["shape"]);
        let shape_b = parse_shape(&input_b["shape"]);
        if shape_a.is_empty() || shape_b.is_empty() {
            continue;
        }
        let arr_a =
            Array::<f64, IxDyn>::from_vec(IxDyn::new(&shape_a), parse_f64_data(&input_a["data"]))
                .unwrap();
        let arr_b =
            Array::<f64, IxDyn>::from_vec(IxDyn::new(&shape_b), parse_f64_data(&input_b["data"]))
                .unwrap();
        let result = func(&arr_a, &arr_b)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_f64_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_f64_slice_ulp(
            result_slice,
            &expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run a unary oracle that returns a boolean array (isnan, isinf, isfinite, signbit).
pub fn run_unary_bool_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<Array<bool, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        if should_skip_f64(input) {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let data = parse_f64_data(&input["data"]);
        if data.is_empty() && shape == [0] {
            continue;
        }
        let arr = Array::<f64, IxDyn>::from_vec(IxDyn::new(&shape), data).unwrap();
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_bool_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_eq!(
            result_slice.len(),
            expected.len(),
            "case '{}': length mismatch",
            case.name
        );
        for (i, (&a, &e)) in result_slice.iter().zip(expected.iter()).enumerate() {
            assert_eq!(
                a, e,
                "case '{}' [element {i}]: actual={a}, expected={e}",
                case.name
            );
        }
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run an oracle test for a function that reduces to a scalar: `fn(Array) -> f64`.
pub fn run_scalar_f64_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<f64>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        if should_skip_f64(input) {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = make_f64_array(input);
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_f64_value(&case.expected["data"]);
        assert_f64_ulp(
            result,
            expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &format!("case '{}'", case.name),
        );
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run oracle for a reduction that returns `IxDyn` (could be scalar or array).
/// The function takes `(array, Option<axis>)`.
pub fn run_reduction_f64_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>, Option<usize>) -> FerrayResult<Array<f64, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        if should_skip_f64(input) {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = make_f64_array(input);
        let axis = case
            .inputs
            .get("axis")
            .and_then(serde_json::Value::as_u64)
            .map(|v| v as usize);
        let result = func(&arr, axis)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected_data = parse_f64_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_f64_slice_ulp(
            result_slice,
            &expected_data,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run oracle for a complex FFT: real input -> complex output.
pub fn run_real_to_complex_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<Array<Complex<f64>, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        let dtype = get_dtype(input);
        if dtype != "float64" {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = make_f64_array(input);
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_complex_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_complex_slice_ulp(
            result_slice,
            &expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    // Previously this ran silently with zero test cases if a fixture
    // happened to have only complex inputs — so a missing dtype
    // handler or a broken fixture would produce a passing test
    // (#320). Match every other runner and require at least one case.
    assert!(
        tested > 0,
        "run_real_to_complex_oracle: no f64 cases were tested in {}",
        path.display()
    );
}

/// Run oracle for a complex->complex FFT.
pub fn run_complex_to_complex_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<Complex<f64>, IxDyn>) -> FerrayResult<Array<Complex<f64>, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        let dtype = get_dtype(input);
        // Accept both real and complex inputs
        let arr = if dtype == "complex128" {
            make_complex_array(input)
        } else if dtype == "float64" {
            // Convert real to complex with zero imaginary
            let data = parse_f64_data(&input["data"]);
            let shape = parse_shape(&input["shape"]);
            let complex_data: Vec<Complex<f64>> =
                data.into_iter().map(|r| Complex::new(r, 0.0)).collect();
            Array::from_vec(IxDyn::new(&shape), complex_data).unwrap()
        } else {
            continue;
        };
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_complex_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_complex_slice_ulp(
            result_slice,
            &expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    assert!(tested > 0, "no test cases found in {}", path.display());
}

// Note: the second (matrix-scalar) run-oracle lives below; keep the
// comment anchor so the file structure is easy to find.

/// Run oracle for a matrix->scalar operation (det, trace, etc.).
pub fn run_matrix_scalar_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<f64>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["a"];
        let dtype = get_dtype(input);
        if dtype != "float64" {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = make_f64_array(input);
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_f64_value(&case.expected["data"]);
        assert_f64_ulp(
            result,
            expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &format!("case '{}'", case.name),
        );
        tested += 1;
    }
    assert!(tested > 0, "no test cases found in {}", path.display());
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // -----------------------------------------------------------------
    // ULP distance (#199, #204)
    // -----------------------------------------------------------------

    #[test]
    fn ulp_distance_f64_equal_values() {
        assert_eq!(ulp_distance_f64(1.0, 1.0), Some(0));
        assert_eq!(ulp_distance_f64(0.0, 0.0), Some(0));
        assert_eq!(ulp_distance_f64(-1.5, -1.5), Some(0));
        assert_eq!(ulp_distance_f64(f64::INFINITY, f64::INFINITY), Some(0));
        assert_eq!(
            ulp_distance_f64(f64::NEG_INFINITY, f64::NEG_INFINITY),
            Some(0)
        );
    }

    #[test]
    fn ulp_distance_f64_signed_zeros_equal() {
        // IEEE 754 says +0.0 == -0.0, and the oracle agrees.
        assert_eq!(ulp_distance_f64(0.0, -0.0), Some(0));
        assert_eq!(ulp_distance_f64(-0.0, 0.0), Some(0));
    }

    #[test]
    fn ulp_distance_f64_one_ulp_step() {
        // next_up gives the next-representable f64 — that's exactly 1 ULP away.
        let a = 1.0f64;
        let b = f64::from_bits(a.to_bits() + 1);
        assert_eq!(ulp_distance_f64(a, b), Some(1));
        assert_eq!(ulp_distance_f64(b, a), Some(1));
    }

    #[test]
    fn ulp_distance_f64_nan_returns_none() {
        assert_eq!(ulp_distance_f64(f64::NAN, 1.0), None);
        assert_eq!(ulp_distance_f64(1.0, f64::NAN), None);
        assert_eq!(ulp_distance_f64(f64::NAN, f64::NAN), None);
    }

    #[test]
    fn ulp_distance_f64_cross_sign_one_vs_minus_one() {
        // #199: this is the case the old code got wrong. The correct
        // cross-sign distance is (|a|.to_bits()) + (|b|.to_bits()),
        // using the sign-magnitude representation of IEEE 754 floats.
        let expected = (1.0f64.to_bits() & !F64_SIGN_MASK) + ((-1.0f64).to_bits() & !F64_SIGN_MASK);
        assert_eq!(ulp_distance_f64(1.0, -1.0), Some(expected));
        assert_eq!(ulp_distance_f64(-1.0, 1.0), Some(expected));
    }

    #[test]
    fn ulp_distance_f64_cross_sign_is_symmetric() {
        // Symmetry sanity check across a range of cross-sign pairs.
        for (a, b) in [
            (1.0f64, -1.0),
            (1e-300, -1e-300),
            (1e100, -1e100),
            (4.25, -6.5),
        ] {
            assert_eq!(
                ulp_distance_f64(a, b),
                ulp_distance_f64(b, a),
                "cross-sign ULP distance should be symmetric for ({a}, {b})"
            );
        }
    }

    #[test]
    fn ulp_distance_f64_cross_sign_is_monotone() {
        // Moving `a` further from zero (same sign) must not decrease the
        // cross-sign distance to a fixed `b` on the other side.
        let b = -1.0f64;
        let d1 = ulp_distance_f64(1.0, b).unwrap();
        let d2 = ulp_distance_f64(2.0, b).unwrap();
        let d3 = ulp_distance_f64(1000.0, b).unwrap();
        assert!(d1 < d2, "d1={d1} d2={d2}");
        assert!(d2 < d3, "d2={d2} d3={d3}");
    }

    #[test]
    fn ulp_distance_f64_near_zero_noise_floor() {
        // Both below the noise floor → considered equal regardless of
        // actual bit distance. 4 * f64::EPSILON ≈ 8.88e-16.
        let tiny = f64::EPSILON;
        let smaller = f64::EPSILON / 2.0;
        assert_eq!(ulp_distance_f64(tiny, smaller), Some(0));
        assert_eq!(ulp_distance_f64(-tiny, tiny), Some(0));
    }

    #[test]
    fn ulp_distance_f32_equal_values() {
        assert_eq!(ulp_distance_f32(1.0, 1.0), Some(0));
        assert_eq!(ulp_distance_f32(0.0, -0.0), Some(0));
    }

    #[test]
    fn ulp_distance_f32_one_ulp_step() {
        let a = 1.0f32;
        let b = f32::from_bits(a.to_bits() + 1);
        assert_eq!(ulp_distance_f32(a, b), Some(1));
    }

    #[test]
    fn ulp_distance_f32_cross_sign_symmetric() {
        let d1 = ulp_distance_f32(1.0, -1.0).unwrap();
        let d2 = ulp_distance_f32(-1.0, 1.0).unwrap();
        assert_eq!(d1, d2);
        let expected = u64::from(1.0f32.to_bits() & !F32_SIGN_MASK)
            + u64::from((-1.0f32).to_bits() & !F32_SIGN_MASK);
        assert_eq!(d1, expected);
    }

    #[test]
    fn ulp_distance_f32_nan_returns_none() {
        assert_eq!(ulp_distance_f32(f32::NAN, 0.0), None);
        assert_eq!(ulp_distance_f32(0.0, f32::NAN), None);
    }

    // ---- parse_f64_value / parse_f64_special ----

    #[test]
    fn parse_f64_value_numeric() {
        assert_eq!(parse_f64_value(&json!(1.5)), 1.5);
        assert_eq!(parse_f64_value(&json!(-3.0)), -3.0);
        assert_eq!(parse_f64_value(&json!(0)), 0.0);
    }

    #[test]
    fn parse_f64_value_nan_string() {
        assert!(parse_f64_value(&json!("NaN")).is_nan());
    }

    #[test]
    fn parse_f64_value_inf_strings() {
        assert_eq!(parse_f64_value(&json!("Inf")), f64::INFINITY);
        assert_eq!(parse_f64_value(&json!("Infinity")), f64::INFINITY);
        assert_eq!(parse_f64_value(&json!("-Inf")), f64::NEG_INFINITY);
        assert_eq!(parse_f64_value(&json!("-Infinity")), f64::NEG_INFINITY);
    }

    // ---- parse_complex_data (#202) ----

    #[test]
    fn parse_complex_data_finite_numbers() {
        let v = json!([
            {"re": 1.0, "im": 2.0},
            {"re": -3.0, "im": 0.5},
        ]);
        let cs = parse_complex_data(&v);
        assert_eq!(cs.len(), 2);
        assert_eq!(cs[0], Complex::new(1.0, 2.0));
        assert_eq!(cs[1], Complex::new(-3.0, 0.5));
    }

    #[test]
    fn parse_complex_data_nan_in_real_part() {
        // Python's JSON serializer writes NaN as the string "NaN" because
        // the JSON grammar doesn't have a NaN literal. Previously this
        // panicked; now it parses cleanly.
        let v = json!([{"re": "NaN", "im": 0.0}]);
        let cs = parse_complex_data(&v);
        assert!(cs[0].re.is_nan());
        assert_eq!(cs[0].im, 0.0);
    }

    #[test]
    fn parse_complex_data_nan_in_imaginary_part() {
        let v = json!([{"re": 0.0, "im": "NaN"}]);
        let cs = parse_complex_data(&v);
        assert_eq!(cs[0].re, 0.0);
        assert!(cs[0].im.is_nan());
    }

    #[test]
    fn parse_complex_data_inf_in_real_part() {
        let v = json!([{"re": "Inf", "im": 0.0}, {"re": "-Inf", "im": 0.0}]);
        let cs = parse_complex_data(&v);
        assert_eq!(cs[0].re, f64::INFINITY);
        assert_eq!(cs[1].re, f64::NEG_INFINITY);
    }

    #[test]
    fn parse_complex_data_mixed_fields() {
        // One string, one number — both fields must be handled independently.
        let v = json!([{"re": "Inf", "im": 3.5}, {"re": -1.25, "im": "NaN"}]);
        let cs = parse_complex_data(&v);
        assert_eq!(cs[0].re, f64::INFINITY);
        assert_eq!(cs[0].im, 3.5);
        assert_eq!(cs[1].re, -1.25);
        assert!(cs[1].im.is_nan());
    }

    #[test]
    fn parse_complex_data_single_object_form() {
        // The Object branch also needs to handle NaN/Inf strings.
        let v = json!({"re": "NaN", "im": "Inf"});
        let cs = parse_complex_data(&v);
        assert_eq!(cs.len(), 1);
        assert!(cs[0].re.is_nan());
        assert_eq!(cs[0].im, f64::INFINITY);
    }
}
